package com.fang.bigdata.metadata.entity;

public class BloodIndex {

    private Integer id;

    private String dataClass;

    private String indicatorName;

    private String is106;

    private String product;

    private String indicatorDefinition;

    private String platform;

    private String position;

    private String entrance;

    private String productPrincipal;

    private String dbSource;

    private String dbIp;

    private String dbSourceName;

    private String dbUsername;

    private String dbTables;

    private String dbSourcePrincipal;

    private String statisticsDimension;

    private String statisticsDimensionTables;

    private String sqlStr;

    private String bigdataPrincipal;

    private String valueSql;

    private String dataType;

    private String dataIp;

    private String dbName;

    private String tableName;

    public BloodIndex() {

    }

    public BloodIndex( String dataClass, String indicatorName, String is106, String product, String indicatorDefinition, String platform, String position, String entrance, String productPrincipal, String dbSource, String dbIp, String dbSourceName, String dbUsername, String dbTables, String dbSourcePrincipal, String statisticsDimension, String statisticsDimensionTables, String sqlStr, String bigdataPrincipal, String valueSql, String dataType, String dataIp, String dbName, String tableName) {
        this.dataClass = dataClass;
        this.indicatorName = indicatorName;
        this.is106 = is106;
        this.product = product;
        this.indicatorDefinition = indicatorDefinition;
        this.platform = platform;
        this.position = position;
        this.entrance = entrance;
        this.productPrincipal = productPrincipal;
        this.dbSource = dbSource;
        this.dbIp = dbIp;
        this.dbSourceName = dbSourceName;
        this.dbUsername = dbUsername;
        this.dbTables = dbTables;
        this.dbSourcePrincipal = dbSourcePrincipal;
        this.statisticsDimension = statisticsDimension;
        this.statisticsDimensionTables = statisticsDimensionTables;
        this.sqlStr = sqlStr;
        this.bigdataPrincipal = bigdataPrincipal;
        this.valueSql = valueSql;
        this.dataType = dataType;
        this.dataIp = dataIp;
        this.dbName = dbName;
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.id
     *
     * @return the value of service_report.id
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.id
     *
     * @param id the value for service_report.id
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.data_class
     *
     * @return the value of service_report.data_class
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getDataClass() {
        return dataClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.data_class
     *
     * @param dataClass the value for service_report.data_class
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setDataClass(String dataClass) {
        this.dataClass = dataClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.indicator_name
     *
     * @return the value of service_report.indicator_name
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getIndicatorName() {
        return indicatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.indicator_name
     *
     * @param indicatorName the value for service_report.indicator_name
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setIndicatorName(String indicatorName) {
        this.indicatorName = indicatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.is106
     *
     * @return the value of service_report.is106
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getIs106() {
        return is106;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.is106
     *
     * @param is106 the value for service_report.is106
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setIs106(String is106) {
        this.is106 = is106;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.product
     *
     * @return the value of service_report.product
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.product
     *
     * @param product the value for service_report.product
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setProduct(String product) {
        this.product = product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.indicator_definition
     *
     * @return the value of service_report.indicator_definition
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getIndicatorDefinition() {
        return indicatorDefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.indicator_definition
     *
     * @param indicatorDefinition the value for service_report.indicator_definition
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setIndicatorDefinition(String indicatorDefinition) {
        this.indicatorDefinition = indicatorDefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.platform
     *
     * @return the value of service_report.platform
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.platform
     *
     * @param platform the value for service_report.platform
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.position
     *
     * @return the value of service_report.position
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.position
     *
     * @param position the value for service_report.position
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.entrance
     *
     * @return the value of service_report.entrance
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getEntrance() {
        return entrance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.entrance
     *
     * @param entrance the value for service_report.entrance
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setEntrance(String entrance) {
        this.entrance = entrance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.product_principal
     *
     * @return the value of service_report.product_principal
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getProductPrincipal() {
        return productPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.product_principal
     *
     * @param productPrincipal the value for service_report.product_principal
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setProductPrincipal(String productPrincipal) {
        this.productPrincipal = productPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.db_source
     *
     * @return the value of service_report.db_source
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getDbSource() {
        return dbSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.db_source
     *
     * @param dbSource the value for service_report.db_source
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setDbSource(String dbSource) {
        this.dbSource = dbSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.db_ip
     *
     * @return the value of service_report.db_ip
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getDbIp() {
        return dbIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.db_ip
     *
     * @param dbIp the value for service_report.db_ip
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setDbIp(String dbIp) {
        this.dbIp = dbIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.db_source_name
     *
     * @return the value of service_report.db_source_name
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getDbSourceName() {
        return dbSourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.db_source_name
     *
     * @param dbSourceName the value for service_report.db_source_name
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setDbSourceName(String dbSourceName) {
        this.dbSourceName = dbSourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.db_username
     *
     * @return the value of service_report.db_username
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getDbUsername() {
        return dbUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.db_username
     *
     * @param dbUsername the value for service_report.db_username
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setDbUsername(String dbUsername) {
        this.dbUsername = dbUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.db_tables
     *
     * @return the value of service_report.db_tables
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getDbTables() {
        return dbTables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.db_tables
     *
     * @param dbTables the value for service_report.db_tables
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setDbTables(String dbTables) {
        this.dbTables = dbTables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.db_source_principal
     *
     * @return the value of service_report.db_source_principal
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getDbSourcePrincipal() {
        return dbSourcePrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.db_source_principal
     *
     * @param dbSourcePrincipal the value for service_report.db_source_principal
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setDbSourcePrincipal(String dbSourcePrincipal) {
        this.dbSourcePrincipal = dbSourcePrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.statistics_dimension
     *
     * @return the value of service_report.statistics_dimension
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getStatisticsDimension() {
        return statisticsDimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.statistics_dimension
     *
     * @param statisticsDimension the value for service_report.statistics_dimension
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setStatisticsDimension(String statisticsDimension) {
        this.statisticsDimension = statisticsDimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.statistics_dimension_tables
     *
     * @return the value of service_report.statistics_dimension_tables
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getStatisticsDimensionTables() {
        return statisticsDimensionTables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.statistics_dimension_tables
     *
     * @param statisticsDimensionTables the value for service_report.statistics_dimension_tables
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setStatisticsDimensionTables(String statisticsDimensionTables) {
        this.statisticsDimensionTables = statisticsDimensionTables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.sql_str
     *
     * @return the value of service_report.sql_str
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getSqlStr() {
        return sqlStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.sql_str
     *
     * @param sqlStr the value for service_report.sql_str
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setSqlStr(String sqlStr) {
        this.sqlStr = sqlStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.bigdata_principal
     *
     * @return the value of service_report.bigdata_principal
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getBigdataPrincipal() {
        return bigdataPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.bigdata_principal
     *
     * @param bigdataPrincipal the value for service_report.bigdata_principal
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setBigdataPrincipal(String bigdataPrincipal) {
        this.bigdataPrincipal = bigdataPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.value_sql
     *
     * @return the value of service_report.value_sql
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getValueSql() {
        return valueSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.value_sql
     *
     * @param valueSql the value for service_report.value_sql
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setValueSql(String valueSql) {
        this.valueSql = valueSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.data_type
     *
     * @return the value of service_report.data_type
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.data_type
     *
     * @param dataType the value for service_report.data_type
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.data_ip
     *
     * @return the value of service_report.data_ip
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getDataIp() {
        return dataIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.data_ip
     *
     * @param dataIp the value for service_report.data_ip
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setDataIp(String dataIp) {
        this.dataIp = dataIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.db_name
     *
     * @return the value of service_report.db_name
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.db_name
     *
     * @param dbName the value for service_report.db_name
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setDbName(String dbName) {
        this.dbName = dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_report.table_name
     *
     * @return the value of service_report.table_name
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_report.table_name
     *
     * @param tableName the value for service_report.table_name
     *
     * @mbggenerated Fri Oct 19 16:46:04 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    @Override
    public String toString() {
        return "BloodIndex{" +
                "id=" + id +
                ", dataClass='" + dataClass + '\'' +
                ", indicatorName='" + indicatorName + '\'' +
                ", is106='" + is106 + '\'' +
                ", product='" + product + '\'' +
                ", indicatorDefinition='" + indicatorDefinition + '\'' +
                ", platform='" + platform + '\'' +
                ", position='" + position + '\'' +
                ", entrance='" + entrance + '\'' +
                ", productPrincipal='" + productPrincipal + '\'' +
                ", dbSource='" + dbSource + '\'' +
                ", dbIp='" + dbIp + '\'' +
                ", dbSourceName='" + dbSourceName + '\'' +
                ", dbUsername='" + dbUsername + '\'' +
                ", dbTables='" + dbTables + '\'' +
                ", dbSourcePrincipal='" + dbSourcePrincipal + '\'' +
                ", statisticsDimension='" + statisticsDimension + '\'' +
                ", statisticsDimensionTables='" + statisticsDimensionTables + '\'' +
                ", sqlStr='" + sqlStr + '\'' +
                ", bigdataPrincipal='" + bigdataPrincipal + '\'' +
                ", valueSql='" + valueSql + '\'' +
                ", dataType='" + dataType + '\'' +
                ", dataIp='" + dataIp + '\'' +
                ", dbName='" + dbName + '\'' +
                ", tableName='" + tableName + '\'' +
                '}';
    }
}